name         'rfletcher-ngrep'
version      '0.0.1'
license      'MIT License'
summary      'A Puppet module for Pipe Viewer'
description  'Install or remove Pipe Viewer'
project_page 'https://github.com/rfletcher/puppet-ngrep'
